table 2014_usa_states
	lineageTag: 23e378b3-521b-4101-96e4-8c8738046779

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: fd7ecf04-2808-4805-9997-d453215fd0e4
		summarizeBy: sum
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 9e887e4a-87d2-4b8c-a266-8a41863efcb1
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Postal
		dataType: string
		lineageTag: af576dd3-6a7b-422c-9c42-ddf0758910c7
		summarizeBy: none
		sourceColumn: Postal

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: int64
		formatString: 0
		lineageTag: 152b086e-6b29-4dda-a9e9-7363fbcb63b5
		summarizeBy: sum
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	partition 2014_usa_states = m
		mode: import
		source =
				let
				    BaseUrl = "https://raw.githubusercontent.com/iam-kanavsharma/datasets/",
				    // Lookup table for environment → URL
				    EnvMap = [
				        dev = "refs/heads/dev/2014_usa_states.csv",
				        qa  = "refs/heads/qa/2014_usa_states.csv",
				        prod = "refs/heads/prod/2014_usa_states.csv"
				    ],
				
				    // Get URL based on selected environment
				    SelectedPath = Record.Field(EnvMap, pEnvironment),
				
				    // Load CSV from selected URL
				    Source = Csv.Document(Web.Contents(BaseUrl & SelectedPath), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"Rank", Int64.Type}, {"State", type text}, {"Postal", type text}, {"Population", Int64.Type}})
				in
				    #"Change Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

